x-base-app: &app-base
  build: .
  restart: unless-stopped
  environment:
    REDIS_URL: "redis://redis:6379"
  depends_on:
    - redis

services:
  nginx:
    image: "nginx:1.29.1-alpine"
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./static:/app/static:ro"
      - "video-storage-vol:/app/media"
    depends_on:
      - web

  web:
    <<: *app-base
    command:
      - "gunicorn"
      - "--worker-class"
      - "gevent"
      - "--bind"
      - "0.0.0.0:8000"
      - "app:app"

  worker:
    <<: *app-base
    volumes:
      - "video-storage-vol:/app/media"
    command:
      - "celery"
      - "--app"
      - "tasks"
      - "worker"
      - "--pool=gevent"
      - "--concurrency=100"
      - "--loglevel=info"

  redis:
    image: "redis:8.2.1-alpine"

volumes:
  video-storage-vol:
